# Generated by Django 5.1.5 on 2025-01-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, help_text='name of student', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.IntegerField(blank=True, help_text='phonenumber of student', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
